/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public partial class PolygonVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<Polygon>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PolygonVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PolygonVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PolygonVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_PolygonVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PolygonVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (Polygon element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Polygon this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(Polygon[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(Polygon[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, Polygon[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<Polygon> System.Collections.Generic.IEnumerable<Polygon>.GetEnumerator() {
    return new PolygonVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new PolygonVectorEnumerator(this);
  }

  public PolygonVectorEnumerator GetEnumerator() {
    return new PolygonVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class PolygonVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<Polygon>
#endif
  {
    private PolygonVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public PolygonVectorEnumerator(PolygonVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Polygon Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (Polygon)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    bridgePINVOKE.PolygonVector_Clear(swigCPtr);
  }

  public void Add(Polygon x) {
    bridgePINVOKE.PolygonVector_Add(swigCPtr, Polygon.getCPtr(x));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = bridgePINVOKE.PolygonVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = bridgePINVOKE.PolygonVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    bridgePINVOKE.PolygonVector_reserve(swigCPtr, n);
  }

  public PolygonVector() : this(bridgePINVOKE.new_PolygonVector__SWIG_0(), true) {
  }

  public PolygonVector(PolygonVector other) : this(bridgePINVOKE.new_PolygonVector__SWIG_1(PolygonVector.getCPtr(other)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public PolygonVector(int capacity) : this(bridgePINVOKE.new_PolygonVector__SWIG_2(capacity), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  private Polygon getitemcopy(int index) {
    Polygon ret = new Polygon(bridgePINVOKE.PolygonVector_getitemcopy(swigCPtr, index), true);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Polygon getitem(int index) {
    Polygon ret = new Polygon(bridgePINVOKE.PolygonVector_getitem(swigCPtr, index), false);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Polygon val) {
    bridgePINVOKE.PolygonVector_setitem(swigCPtr, index, Polygon.getCPtr(val));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(PolygonVector values) {
    bridgePINVOKE.PolygonVector_AddRange(swigCPtr, PolygonVector.getCPtr(values));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public PolygonVector GetRange(int index, int count) {
    IntPtr cPtr = bridgePINVOKE.PolygonVector_GetRange(swigCPtr, index, count);
    PolygonVector ret = (cPtr == IntPtr.Zero) ? null : new PolygonVector(cPtr, true);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Polygon x) {
    bridgePINVOKE.PolygonVector_Insert(swigCPtr, index, Polygon.getCPtr(x));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, PolygonVector values) {
    bridgePINVOKE.PolygonVector_InsertRange(swigCPtr, index, PolygonVector.getCPtr(values));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    bridgePINVOKE.PolygonVector_RemoveAt(swigCPtr, index);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    bridgePINVOKE.PolygonVector_RemoveRange(swigCPtr, index, count);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public static PolygonVector Repeat(Polygon value, int count) {
    IntPtr cPtr = bridgePINVOKE.PolygonVector_Repeat(Polygon.getCPtr(value), count);
    PolygonVector ret = (cPtr == IntPtr.Zero) ? null : new PolygonVector(cPtr, true);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    bridgePINVOKE.PolygonVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    bridgePINVOKE.PolygonVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, PolygonVector values) {
    bridgePINVOKE.PolygonVector_SetRange(swigCPtr, index, PolygonVector.getCPtr(values));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
