/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public class ChokepointGetSidesPair : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChokepointGetSidesPair(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ChokepointGetSidesPair obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChokepointGetSidesPair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_ChokepointGetSidesPair(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ChokepointGetSidesPair() : this(bridgePINVOKE.new_ChokepointGetSidesPair__SWIG_0(), true) {
  }

  public ChokepointGetSidesPair(Position t, Position u) : this(bridgePINVOKE.new_ChokepointGetSidesPair__SWIG_1(Position.getCPtr(t), Position.getCPtr(u)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public ChokepointGetSidesPair(ChokepointGetSidesPair p) : this(bridgePINVOKE.new_ChokepointGetSidesPair__SWIG_2(ChokepointGetSidesPair.getCPtr(p)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public Position first {
    set {
      bridgePINVOKE.ChokepointGetSidesPair_first_set(swigCPtr, Position.getCPtr(value));
    } 
    get {
      IntPtr cPtr = bridgePINVOKE.ChokepointGetSidesPair_first_get(swigCPtr);
      Position ret = (cPtr == IntPtr.Zero) ? null : new Position(cPtr, false);
      return ret;
    } 
  }

  public Position second {
    set {
      bridgePINVOKE.ChokepointGetSidesPair_second_set(swigCPtr, Position.getCPtr(value));
    } 
    get {
      IntPtr cPtr = bridgePINVOKE.ChokepointGetSidesPair_second_get(swigCPtr);
      Position ret = (cPtr == IntPtr.Zero) ? null : new Position(cPtr, false);
      return ret;
    } 
  }

}

}
