/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DamageTypeSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DamageTypeSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DamageTypeSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DamageTypeSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_DamageTypeSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DamageTypeSet(SWIGTYPE_p_std__setT_BWAPI__DamageType_t original) : this(bridgePINVOKE.new_DamageTypeSet(SWIGTYPE_p_std__setT_BWAPI__DamageType_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.DamageTypeSet_size(swigCPtr);
    return ret;
  }

  public bool contains(DamageType item) {
    bool ret = bridgePINVOKE.DamageTypeSet_contains(swigCPtr, DamageType.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool add(DamageType item) {
    bool ret = bridgePINVOKE.DamageTypeSet_add(swigCPtr, DamageType.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void clear() {
    bridgePINVOKE.DamageTypeSet_clear(swigCPtr);
  }

  public bool remove(DamageType item) {
    bool ret = bridgePINVOKE.DamageTypeSet_remove(swigCPtr, DamageType.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
