/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class DamageType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DamageType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DamageType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DamageType() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_DamageType(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public DamageType() : this(bridgePINVOKE.new_DamageType__SWIG_0(), true) {
  }

  public DamageType(int id) : this(bridgePINVOKE.new_DamageType__SWIG_1(id), true) {
  }

  public DamageType(DamageType other) : this(bridgePINVOKE.new_DamageType__SWIG_2(DamageType.getCPtr(other)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public DamageType opAssign(DamageType other) {
    DamageType ret = new DamageType(bridgePINVOKE.DamageType_opAssign(swigCPtr, DamageType.getCPtr(other)), false);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opEquals(DamageType other) {
    bool ret = bridgePINVOKE.DamageType_opEquals(swigCPtr, DamageType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opNotEquals(DamageType other) {
    bool ret = bridgePINVOKE.DamageType_opNotEquals(swigCPtr, DamageType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opLessThan(DamageType other) {
    bool ret = bridgePINVOKE.DamageType_opLessThan(swigCPtr, DamageType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getID() {
    int ret = bridgePINVOKE.DamageType_getID(swigCPtr);
    return ret;
  }

  public string getName() {
    string ret = bridgePINVOKE.DamageType_getName(swigCPtr);
    return ret;
  }

}
