/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ForceSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ForceSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ForceSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ForceSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_ForceSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public ForceSet(SWIGTYPE_p_std__setT_BWAPI__Force_p_t original) : this(bridgePINVOKE.new_ForceSet(SWIGTYPE_p_std__setT_BWAPI__Force_p_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.ForceSet_size(swigCPtr);
    return ret;
  }

  public bool contains(Force item) {
    bool ret = bridgePINVOKE.ForceSet_contains(swigCPtr, Force.getCPtr(item));
    return ret;
  }

  public bool add(Force item) {
    bool ret = bridgePINVOKE.ForceSet_add(swigCPtr, Force.getCPtr(item));
    return ret;
  }

  public void clear() {
    bridgePINVOKE.ForceSet_clear(swigCPtr);
  }

  public bool remove(Force item) {
    bool ret = bridgePINVOKE.ForceSet_remove(swigCPtr, Force.getCPtr(item));
    return ret;
  }

}
