/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public class OrderSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OrderSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(OrderSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~OrderSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_OrderSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public OrderSet(SWIGTYPE_p_std__setT_BWAPI__Order_t original) : this(bridgePINVOKE.new_OrderSet(SWIGTYPE_p_std__setT_BWAPI__Order_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.OrderSet_size(swigCPtr);
    return ret;
  }

  public bool contains(Order item) {
    bool ret = bridgePINVOKE.OrderSet_contains(swigCPtr, Order.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool add(Order item) {
    bool ret = bridgePINVOKE.OrderSet_add(swigCPtr, Order.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void clear() {
    bridgePINVOKE.OrderSet_clear(swigCPtr);
  }

  public bool remove(Order item) {
    bool ret = bridgePINVOKE.OrderSet_remove(swigCPtr, Order.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
