/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public class PlayerSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PlayerSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PlayerSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PlayerSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_PlayerSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PlayerSet(SWIGTYPE_p_std__setT_BWAPI__Player_p_t original) : this(bridgePINVOKE.new_PlayerSet(SWIGTYPE_p_std__setT_BWAPI__Player_p_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.PlayerSet_size(swigCPtr);
    return ret;
  }

  public bool contains(Player item) {
    bool ret = bridgePINVOKE.PlayerSet_contains(swigCPtr, Player.getCPtr(item));
    return ret;
  }

  public bool add(Player item) {
    bool ret = bridgePINVOKE.PlayerSet_add(swigCPtr, Player.getCPtr(item));
    return ret;
  }

  public void clear() {
    bridgePINVOKE.PlayerSet_clear(swigCPtr);
  }

  public bool remove(Player item) {
    bool ret = bridgePINVOKE.PlayerSet_remove(swigCPtr, Player.getCPtr(item));
    return ret;
  }

}

}
