/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PositionVector : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PositionVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PositionVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PositionVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_PositionVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PositionVector(SWIGTYPE_p_std__vectorT_BWAPI__Position_t original) : this(bridgePINVOKE.new_PositionVector(SWIGTYPE_p_std__vectorT_BWAPI__Position_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.PositionVector_size(swigCPtr);
    return ret;
  }

  public void add(int index, Position item) {
    bridgePINVOKE.PositionVector_add(swigCPtr, index, Position.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public void clear() {
    bridgePINVOKE.PositionVector_clear(swigCPtr);
  }

  public Position set(int index, Position item) {
    Position ret = new Position(bridgePINVOKE.PositionVector_set(swigCPtr, index, Position.getCPtr(item)), true);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Position remove(int index) {
    Position ret = new Position(bridgePINVOKE.PositionVector_remove(swigCPtr, index), true);
    return ret;
  }

  public Position get(int index) {
    Position ret = new Position(bridgePINVOKE.PositionVector_get(swigCPtr, index), true);
    return ret;
  }

}
