/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TechTypeConstantSetIterator : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TechTypeConstantSetIterator(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TechTypeConstantSetIterator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TechTypeConstantSetIterator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_TechTypeConstantSetIterator(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TechTypeConstantSetIterator(SWIGTYPE_p_std__setT_BWAPI__TechType_const_p_t original) : this(bridgePINVOKE.new_TechTypeConstantSetIterator(SWIGTYPE_p_std__setT_BWAPI__TechType_const_p_t.getCPtr(original)), true) {
  }

  public bool hasNext() {
    bool ret = bridgePINVOKE.TechTypeConstantSetIterator_hasNext(swigCPtr);
    return ret;
  }

  public TechType next() {
    IntPtr cPtr = bridgePINVOKE.TechTypeConstantSetIterator_next(swigCPtr);
    TechType ret = (cPtr == IntPtr.Zero) ? null : new TechType(cPtr, false);
    return ret;
  }

}
