/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public class TechType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TechType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TechType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TechType() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_TechType(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is TechType)
      equal = (((TechType)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(TechType obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(TechType obj1, TechType obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(TechType obj1, TechType obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public TechType() : this(bridgePINVOKE.new_TechType__SWIG_0(), true) {
  }

  public TechType(int id) : this(bridgePINVOKE.new_TechType__SWIG_1(id), true) {
  }

  public TechType(TechType other) : this(bridgePINVOKE.new_TechType__SWIG_2(TechType.getCPtr(other)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public TechType opAssign(TechType other) {
    TechType ret = new TechType(bridgePINVOKE.TechType_opAssign(swigCPtr, TechType.getCPtr(other)), false);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opEquals(TechType other) {
    bool ret = bridgePINVOKE.TechType_opEquals(swigCPtr, TechType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opNotEquals(TechType other) {
    bool ret = bridgePINVOKE.TechType_opNotEquals(swigCPtr, TechType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opLessThan(TechType other) {
    bool ret = bridgePINVOKE.TechType_opLessThan(swigCPtr, TechType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getID() {
    int ret = bridgePINVOKE.TechType_getID(swigCPtr);
    return ret;
  }

  public string getName() {
    string ret = bridgePINVOKE.TechType_getName(swigCPtr);
    return ret;
  }

  public int mineralPrice() {
    int ret = bridgePINVOKE.TechType_mineralPrice(swigCPtr);
    return ret;
  }

  public int gasPrice() {
    int ret = bridgePINVOKE.TechType_gasPrice(swigCPtr);
    return ret;
  }

  public int energyUsed() {
    int ret = bridgePINVOKE.TechType_energyUsed(swigCPtr);
    return ret;
  }

  public UnitType whatResearches() {
    IntPtr cPtr = bridgePINVOKE.TechType_whatResearches(swigCPtr);
    UnitType ret = (cPtr == IntPtr.Zero) ? null : new UnitType(cPtr, false);
    return ret;
  }

  public WeaponType getWeapon() {
    IntPtr cPtr = bridgePINVOKE.TechType_getWeapon(swigCPtr);
    WeaponType ret = (cPtr == IntPtr.Zero) ? null : new WeaponType(cPtr, false);
    return ret;
  }

  public UnitTypePtrSet whatUses() {
    UnitTypePtrSet ret = new UnitTypePtrSet(bridgePINVOKE.TechType_whatUses(swigCPtr), false);
    return ret;
  }

}

}
