/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class UnitSizeTypeSetIterator : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UnitSizeTypeSetIterator(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UnitSizeTypeSetIterator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnitSizeTypeSetIterator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_UnitSizeTypeSetIterator(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public UnitSizeTypeSetIterator(SWIGTYPE_p_std__setT_BWAPI__UnitSizeType_t original) : this(bridgePINVOKE.new_UnitSizeTypeSetIterator(SWIGTYPE_p_std__setT_BWAPI__UnitSizeType_t.getCPtr(original)), true) {
  }

  public bool hasNext() {
    bool ret = bridgePINVOKE.UnitSizeTypeSetIterator_hasNext(swigCPtr);
    return ret;
  }

  public UnitSizeType next() {
    UnitSizeType ret = new UnitSizeType(bridgePINVOKE.UnitSizeTypeSetIterator_next(swigCPtr), true);
    return ret;
  }

}
