/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public class UnitTypeSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UnitTypeSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UnitTypeSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnitTypeSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_UnitTypeSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public UnitTypeSet(SWIGTYPE_p_std__setT_BWAPI__UnitType_t original) : this(bridgePINVOKE.new_UnitTypeSet(SWIGTYPE_p_std__setT_BWAPI__UnitType_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.UnitTypeSet_size(swigCPtr);
    return ret;
  }

  public bool contains(UnitType item) {
    bool ret = bridgePINVOKE.UnitTypeSet_contains(swigCPtr, UnitType.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool add(UnitType item) {
    bool ret = bridgePINVOKE.UnitTypeSet_add(swigCPtr, UnitType.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void clear() {
    bridgePINVOKE.UnitTypeSet_clear(swigCPtr);
  }

  public bool remove(UnitType item) {
    bool ret = bridgePINVOKE.UnitTypeSet_remove(swigCPtr, UnitType.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
