/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public partial class UnitTypePtrSet : IDisposable 
#if !SWIG_DOTNET_1
    , System.Collections.Generic.ICollection<UnitType>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UnitTypePtrSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UnitTypePtrSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UnitTypePtrSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_UnitTypePtrSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }


  
  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsReadOnly {
    get { 
      return false; 
    }
  }

#if !SWIG_DOTNET_1
 public System.Collections.Generic.ICollection<UnitType> Values {
    get {
      System.Collections.Generic.ICollection<UnitType> values = new System.Collections.Generic.List<UnitType>();
      IntPtr iter = create_iterator_begin();
      try {
        while (true) {
          values.Add(get_next_key(iter));
        }
      } catch (ArgumentOutOfRangeException) {
      }
      return values;
    }
  }
 
  public bool Contains(UnitType item) {
    if ( ContainsKey(item)) {
      return true;
    } else {
      return false;
    }
  }

  public void CopyTo(UnitType[] array) {
    CopyTo(array, 0);
  }

  public void CopyTo( UnitType[] array, int arrayIndex) {
    if (array == null)
      throw new ArgumentNullException("array");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (arrayIndex+this.Count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");

   System.Collections.Generic.IList<UnitType> keyList = new System.Collections.Generic.List<UnitType>(this.Values);
    for (int i = 0; i < this.Count; i++) {
      UnitType currentKey = keyList[i];
      array.SetValue( currentKey, arrayIndex+i);
    }
  }

  System.Collections.Generic.IEnumerator< UnitType> System.Collections.Generic.IEnumerable<UnitType>.GetEnumerator() {
    return new UnitTypePtrSetEnumerator(this);
  }

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new UnitTypePtrSetEnumerator(this);
  }

  public UnitTypePtrSetEnumerator GetEnumerator() {
    return new UnitTypePtrSetEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class UnitTypePtrSetEnumerator : System.Collections.IEnumerator, 
      System.Collections.Generic.IEnumerator< UnitType>
  {
    private UnitTypePtrSet collectionRef;
    private System.Collections.Generic.IList<UnitType> keyCollection;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public UnitTypePtrSetEnumerator(UnitTypePtrSet collection) {
      collectionRef = collection;
      keyCollection = new System.Collections.Generic.List<UnitType>(collection.Values);
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public  UnitType Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return ( UnitType)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        UnitType currentKey = keyCollection[currentIndex];
        currentObject = currentKey;
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }
#endif
  

  public UnitTypePtrSet() : this(bridgePINVOKE.new_UnitTypePtrSet__SWIG_0(), true) {
  }

  public UnitTypePtrSet(UnitTypePtrSet other) : this(bridgePINVOKE.new_UnitTypePtrSet__SWIG_1(UnitTypePtrSet.getCPtr(other)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = bridgePINVOKE.UnitTypePtrSet_size(swigCPtr);
    return ret;
  }

  public bool empty() {
    bool ret = bridgePINVOKE.UnitTypePtrSet_empty(swigCPtr);
    return ret;
  }

  public void Clear() {
    bridgePINVOKE.UnitTypePtrSet_Clear(swigCPtr);
  }

  public UnitType getitem(UnitType key) {
    IntPtr cPtr = bridgePINVOKE.UnitTypePtrSet_getitem(swigCPtr, UnitType.getCPtr(key));
    UnitType ret = (cPtr == IntPtr.Zero) ? null : new UnitType(cPtr, false);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ContainsKey(UnitType key) {
    bool ret = bridgePINVOKE.UnitTypePtrSet_ContainsKey(swigCPtr, UnitType.getCPtr(key));
    return ret;
  }

  public void Add(UnitType key) {
    bridgePINVOKE.UnitTypePtrSet_Add(swigCPtr, UnitType.getCPtr(key));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Remove(UnitType key) {
    bool ret = bridgePINVOKE.UnitTypePtrSet_Remove(swigCPtr, UnitType.getCPtr(key));
    return ret;
  }

  public IntPtr create_iterator_begin() {
    IntPtr ret = bridgePINVOKE.UnitTypePtrSet_create_iterator_begin(swigCPtr);
    return ret;
  }

  public UnitType get_next_key(IntPtr swigiterator) {
    IntPtr cPtr = bridgePINVOKE.UnitTypePtrSet_get_next_key(swigCPtr, swigiterator);
    UnitType ret = (cPtr == IntPtr.Zero) ? null : new UnitType(cPtr, false);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
