/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public partial class Game : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Game(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Game obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Game() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKEProxy.delete_Game(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  
public override int GetHashCode()
{
   return this.swigCPtr.Handle.GetHashCode();
}

public override bool Equals(object obj)
{
    bool equal = false;
    if (obj is Game)
      equal = (((Game)obj).swigCPtr.Handle == this.swigCPtr.Handle);
    return equal;
}
  
public bool Equals(Game obj) 
{
    if (obj == null) return false;
    return (obj.swigCPtr.Handle == this.swigCPtr.Handle);
}

public static bool operator ==(Game obj1, Game obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return true;
    if (object.ReferenceEquals(obj1, null)) return false;
    if (object.ReferenceEquals(obj2, null)) return false;
   
    return obj1.Equals(obj2);
}

public static bool operator !=(Game obj1, Game obj2)
{
    if (object.ReferenceEquals(obj1, obj2)) return false;
    if (object.ReferenceEquals(obj1, null)) return true;
    if (object.ReferenceEquals(obj2, null)) return true;

    return !obj1.Equals(obj2);
}




  public virtual ForcePtrSet getForces() {
    ForcePtrSet ret = new ForcePtrSet(bridgePINVOKEProxy.Game_getForces(swigCPtr), false);
    return ret;
  }

  public virtual PlayerPtrSet getPlayers() {
    PlayerPtrSet ret = new PlayerPtrSet(bridgePINVOKEProxy.Game_getPlayers(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getAllUnits() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getAllUnits(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getMinerals() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getMinerals(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getGeysers() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getGeysers(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getNeutralUnits() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getNeutralUnits(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getStaticMinerals() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getStaticMinerals(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getStaticGeysers() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getStaticGeysers(swigCPtr), false);
    return ret;
  }

  public virtual UnitSet getStaticNeutralUnits() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getStaticNeutralUnits(swigCPtr), false);
    return ret;
  }

  public virtual int getLatency() {
    int ret = bridgePINVOKEProxy.Game_getLatency(swigCPtr);
    return ret;
  }

  public virtual int getFrameCount() {
    int ret = bridgePINVOKEProxy.Game_getFrameCount(swigCPtr);
    return ret;
  }

  public virtual int getMouseX() {
    int ret = bridgePINVOKEProxy.Game_getMouseX(swigCPtr);
    return ret;
  }

  public virtual int getMouseY() {
    int ret = bridgePINVOKEProxy.Game_getMouseY(swigCPtr);
    return ret;
  }

  public virtual Position getMousePosition() {
    Position ret = new Position(bridgePINVOKEProxy.Game_getMousePosition(swigCPtr), true);
    return ret;
  }

  public virtual bool getMouseState(MouseButton button) {
    bool ret = bridgePINVOKEProxy.Game_getMouseState__SWIG_0(swigCPtr, (int)button);
    return ret;
  }

  public virtual bool getMouseState(int button) {
    bool ret = bridgePINVOKEProxy.Game_getMouseState__SWIG_1(swigCPtr, button);
    return ret;
  }

  public virtual bool getKeyState(Key key) {
    bool ret = bridgePINVOKEProxy.Game_getKeyState__SWIG_0(swigCPtr, (int)key);
    return ret;
  }

  public virtual bool getKeyState(int key) {
    bool ret = bridgePINVOKEProxy.Game_getKeyState__SWIG_1(swigCPtr, key);
    return ret;
  }

  public virtual int getScreenX() {
    int ret = bridgePINVOKEProxy.Game_getScreenX(swigCPtr);
    return ret;
  }

  public virtual int getScreenY() {
    int ret = bridgePINVOKEProxy.Game_getScreenY(swigCPtr);
    return ret;
  }

  public virtual Position getScreenPosition() {
    Position ret = new Position(bridgePINVOKEProxy.Game_getScreenPosition(swigCPtr), true);
    return ret;
  }

  public virtual void setScreenPosition(int x, int y) {
    bridgePINVOKEProxy.Game_setScreenPosition__SWIG_0(swigCPtr, x, y);
  }

  public virtual void setScreenPosition(Position p) {
    bridgePINVOKEProxy.Game_setScreenPosition__SWIG_1(swigCPtr, Position.getCPtr(p));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void pingMinimap(int x, int y) {
    bridgePINVOKEProxy.Game_pingMinimap__SWIG_0(swigCPtr, x, y);
  }

  public virtual void pingMinimap(Position p) {
    bridgePINVOKEProxy.Game_pingMinimap__SWIG_1(swigCPtr, Position.getCPtr(p));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual bool isFlagEnabled(int flag) {
    bool ret = bridgePINVOKEProxy.Game_isFlagEnabled(swigCPtr, flag);
    return ret;
  }

  public virtual void enableFlag(int flag) {
    bridgePINVOKEProxy.Game_enableFlag(swigCPtr, flag);
  }

  public virtual UnitSet unitsOnTile(int x, int y) {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_unitsOnTile(swigCPtr, x, y), false);
    return ret;
  }

  public virtual Error getLastError() {
    Error ret = new Error(bridgePINVOKEProxy.Game_getLastError(swigCPtr), true);
    return ret;
  }

  public virtual int mapWidth() {
    int ret = bridgePINVOKEProxy.Game_mapWidth(swigCPtr);
    return ret;
  }

  public virtual int mapHeight() {
    int ret = bridgePINVOKEProxy.Game_mapHeight(swigCPtr);
    return ret;
  }

  public virtual string mapFilename() {
    string ret = bridgePINVOKEProxy.Game_mapFilename(swigCPtr);
    return ret;
  }

  public virtual string mapName() {
    string ret = bridgePINVOKEProxy.Game_mapName(swigCPtr);
    return ret;
  }

  public virtual int getMapHash() {
    int ret = bridgePINVOKEProxy.Game_getMapHash(swigCPtr);
    return ret;
  }

  public virtual int getGroundHeight(int x, int y) {
    int ret = bridgePINVOKEProxy.Game_getGroundHeight(swigCPtr, x, y);
    return ret;
  }

  public virtual bool isWalkable(int x, int y) {
    bool ret = bridgePINVOKEProxy.Game_isWalkable(swigCPtr, x, y);
    return ret;
  }

  public virtual bool isBuildable(int x, int y) {
    bool ret = bridgePINVOKEProxy.Game_isBuildable__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public virtual bool isVisible(int x, int y) {
    bool ret = bridgePINVOKEProxy.Game_isVisible__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public virtual bool isExplored(int x, int y) {
    bool ret = bridgePINVOKEProxy.Game_isExplored__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public virtual bool hasCreep(int x, int y) {
    bool ret = bridgePINVOKEProxy.Game_hasCreep__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public virtual bool hasPower(int x, int y, int tileWidth, int tileHeight) {
    bool ret = bridgePINVOKEProxy.Game_hasPower__SWIG_0(swigCPtr, x, y, tileWidth, tileHeight);
    return ret;
  }

  public virtual bool isBuildable(TilePosition position) {
    bool ret = bridgePINVOKEProxy.Game_isBuildable__SWIG_1(swigCPtr, TilePosition.getCPtr(position));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool isVisible(TilePosition position) {
    bool ret = bridgePINVOKEProxy.Game_isVisible__SWIG_1(swigCPtr, TilePosition.getCPtr(position));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool isExplored(TilePosition position) {
    bool ret = bridgePINVOKEProxy.Game_isExplored__SWIG_1(swigCPtr, TilePosition.getCPtr(position));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool hasCreep(TilePosition position) {
    bool ret = bridgePINVOKEProxy.Game_hasCreep__SWIG_1(swigCPtr, TilePosition.getCPtr(position));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool hasPower(TilePosition position, int tileWidth, int tileHeight) {
    bool ret = bridgePINVOKEProxy.Game_hasPower__SWIG_1(swigCPtr, TilePosition.getCPtr(position), tileWidth, tileHeight);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool canBuildHere(Unit builder, TilePosition position, UnitType type) {
    bool ret = bridgePINVOKEProxy.Game_canBuildHere(swigCPtr, Unit.getCPtr(builder), TilePosition.getCPtr(position), UnitType.getCPtr(type));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool canMake(Unit builder, UnitType type) {
    bool ret = bridgePINVOKEProxy.Game_canMake(swigCPtr, Unit.getCPtr(builder), UnitType.getCPtr(type));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool canResearch(Unit unit, TechType type) {
    bool ret = bridgePINVOKEProxy.Game_canResearch(swigCPtr, Unit.getCPtr(unit), TechType.getCPtr(type));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool canUpgrade(Unit unit, UpgradeType type) {
    bool ret = bridgePINVOKEProxy.Game_canUpgrade(swigCPtr, Unit.getCPtr(unit), UpgradeType.getCPtr(type));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual TilePositionSet getStartLocations() {
    TilePositionSet ret = new TilePositionSet(bridgePINVOKEProxy.Game_getStartLocations(swigCPtr), false);
    return ret;
  }

  public virtual void printf(string text) {
    bridgePINVOKEProxy.Game_printf(swigCPtr, text);
  }

  public virtual void sendText(string text) {
    bridgePINVOKEProxy.Game_sendText(swigCPtr, text);
  }

  public virtual void changeRace(Race race) {
    bridgePINVOKEProxy.Game_changeRace(swigCPtr, Race.getCPtr(race));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual bool isMultiplayer() {
    bool ret = bridgePINVOKEProxy.Game_isMultiplayer(swigCPtr);
    return ret;
  }

  public virtual bool isPaused() {
    bool ret = bridgePINVOKEProxy.Game_isPaused(swigCPtr);
    return ret;
  }

  public virtual bool isReplay() {
    bool ret = bridgePINVOKEProxy.Game_isReplay(swigCPtr);
    return ret;
  }

  public virtual void startGame() {
    bridgePINVOKEProxy.Game_startGame(swigCPtr);
  }

  public virtual void pauseGame() {
    bridgePINVOKEProxy.Game_pauseGame(swigCPtr);
  }

  public virtual void resumeGame() {
    bridgePINVOKEProxy.Game_resumeGame(swigCPtr);
  }

  public virtual void leaveGame() {
    bridgePINVOKEProxy.Game_leaveGame(swigCPtr);
  }

  public virtual void restartGame() {
    bridgePINVOKEProxy.Game_restartGame(swigCPtr);
  }

  public virtual void setLocalSpeed(int speed) {
    bridgePINVOKEProxy.Game_setLocalSpeed__SWIG_0(swigCPtr, speed);
  }

  public virtual void setLocalSpeed() {
    bridgePINVOKEProxy.Game_setLocalSpeed__SWIG_1(swigCPtr);
  }

  public virtual UnitSet getSelectedUnits() {
    UnitSet ret = new UnitSet(bridgePINVOKEProxy.Game_getSelectedUnits(swigCPtr), false);
    return ret;
  }

  public virtual Player self() {
    IntPtr cPtr = bridgePINVOKEProxy.Game_self(swigCPtr);
    Player ret = (cPtr == IntPtr.Zero) ? null : new Player(cPtr, false);
    return ret;
  }

  public virtual Player enemy() {
    IntPtr cPtr = bridgePINVOKEProxy.Game_enemy(swigCPtr);
    Player ret = (cPtr == IntPtr.Zero) ? null : new Player(cPtr, false);
    return ret;
  }

  public virtual void drawText(int ctype, int x, int y, string text) {
    bridgePINVOKEProxy.Game_drawText(swigCPtr, ctype, x, y, text);
  }

  public virtual void drawTextMap(int x, int y, string text) {
    bridgePINVOKEProxy.Game_drawTextMap(swigCPtr, x, y, text);
  }

  public virtual void drawTextMouse(int x, int y, string text) {
    bridgePINVOKEProxy.Game_drawTextMouse(swigCPtr, x, y, text);
  }

  public virtual void drawTextScreen(int x, int y, string text) {
    bridgePINVOKEProxy.Game_drawTextScreen(swigCPtr, x, y, text);
  }

  public virtual void drawBox(int ctype, int left, int top, int right, int bottom, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawBox__SWIG_0(swigCPtr, ctype, left, top, right, bottom, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBox(int ctype, int left, int top, int right, int bottom, Color color) {
    bridgePINVOKEProxy.Game_drawBox__SWIG_1(swigCPtr, ctype, left, top, right, bottom, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBoxMap(int left, int top, int right, int bottom, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawBoxMap__SWIG_0(swigCPtr, left, top, right, bottom, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBoxMap(int left, int top, int right, int bottom, Color color) {
    bridgePINVOKEProxy.Game_drawBoxMap__SWIG_1(swigCPtr, left, top, right, bottom, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBoxMouse(int left, int top, int right, int bottom, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawBoxMouse__SWIG_0(swigCPtr, left, top, right, bottom, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBoxMouse(int left, int top, int right, int bottom, Color color) {
    bridgePINVOKEProxy.Game_drawBoxMouse__SWIG_1(swigCPtr, left, top, right, bottom, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBoxScreen(int left, int top, int right, int bottom, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawBoxScreen__SWIG_0(swigCPtr, left, top, right, bottom, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawBoxScreen(int left, int top, int right, int bottom, Color color) {
    bridgePINVOKEProxy.Game_drawBoxScreen__SWIG_1(swigCPtr, left, top, right, bottom, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangle(int ctype, int ax, int ay, int bx, int by, int cx, int cy, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawTriangle__SWIG_0(swigCPtr, ctype, ax, ay, bx, by, cx, cy, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangle(int ctype, int ax, int ay, int bx, int by, int cx, int cy, Color color) {
    bridgePINVOKEProxy.Game_drawTriangle__SWIG_1(swigCPtr, ctype, ax, ay, bx, by, cx, cy, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangleMap(int ax, int ay, int bx, int by, int cx, int cy, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawTriangleMap__SWIG_0(swigCPtr, ax, ay, bx, by, cx, cy, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangleMap(int ax, int ay, int bx, int by, int cx, int cy, Color color) {
    bridgePINVOKEProxy.Game_drawTriangleMap__SWIG_1(swigCPtr, ax, ay, bx, by, cx, cy, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangleMouse(int ax, int ay, int bx, int by, int cx, int cy, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawTriangleMouse__SWIG_0(swigCPtr, ax, ay, bx, by, cx, cy, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangleMouse(int ax, int ay, int bx, int by, int cx, int cy, Color color) {
    bridgePINVOKEProxy.Game_drawTriangleMouse__SWIG_1(swigCPtr, ax, ay, bx, by, cx, cy, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangleScreen(int ax, int ay, int bx, int by, int cx, int cy, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawTriangleScreen__SWIG_0(swigCPtr, ax, ay, bx, by, cx, cy, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawTriangleScreen(int ax, int ay, int bx, int by, int cx, int cy, Color color) {
    bridgePINVOKEProxy.Game_drawTriangleScreen__SWIG_1(swigCPtr, ax, ay, bx, by, cx, cy, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircle(int ctype, int x, int y, int radius, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawCircle__SWIG_0(swigCPtr, ctype, x, y, radius, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircle(int ctype, int x, int y, int radius, Color color) {
    bridgePINVOKEProxy.Game_drawCircle__SWIG_1(swigCPtr, ctype, x, y, radius, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircleMap(int x, int y, int radius, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawCircleMap__SWIG_0(swigCPtr, x, y, radius, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircleMap(int x, int y, int radius, Color color) {
    bridgePINVOKEProxy.Game_drawCircleMap__SWIG_1(swigCPtr, x, y, radius, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircleMouse(int x, int y, int radius, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawCircleMouse__SWIG_0(swigCPtr, x, y, radius, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircleMouse(int x, int y, int radius, Color color) {
    bridgePINVOKEProxy.Game_drawCircleMouse__SWIG_1(swigCPtr, x, y, radius, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircleScreen(int x, int y, int radius, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawCircleScreen__SWIG_0(swigCPtr, x, y, radius, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircleScreen(int x, int y, int radius, Color color) {
    bridgePINVOKEProxy.Game_drawCircleScreen__SWIG_1(swigCPtr, x, y, radius, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipse(int ctype, int x, int y, int xrad, int yrad, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawEllipse__SWIG_0(swigCPtr, ctype, x, y, xrad, yrad, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipse(int ctype, int x, int y, int xrad, int yrad, Color color) {
    bridgePINVOKEProxy.Game_drawEllipse__SWIG_1(swigCPtr, ctype, x, y, xrad, yrad, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipseMap(int x, int y, int xrad, int yrad, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawEllipseMap__SWIG_0(swigCPtr, x, y, xrad, yrad, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipseMap(int x, int y, int xrad, int yrad, Color color) {
    bridgePINVOKEProxy.Game_drawEllipseMap__SWIG_1(swigCPtr, x, y, xrad, yrad, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipseMouse(int x, int y, int xrad, int yrad, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawEllipseMouse__SWIG_0(swigCPtr, x, y, xrad, yrad, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipseMouse(int x, int y, int xrad, int yrad, Color color) {
    bridgePINVOKEProxy.Game_drawEllipseMouse__SWIG_1(swigCPtr, x, y, xrad, yrad, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipseScreen(int x, int y, int xrad, int yrad, Color color, bool isSolid) {
    bridgePINVOKEProxy.Game_drawEllipseScreen__SWIG_0(swigCPtr, x, y, xrad, yrad, Color.getCPtr(color), isSolid);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawEllipseScreen(int x, int y, int xrad, int yrad, Color color) {
    bridgePINVOKEProxy.Game_drawEllipseScreen__SWIG_1(swigCPtr, x, y, xrad, yrad, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawDot(int ctype, int x, int y, Color color) {
    bridgePINVOKEProxy.Game_drawDot(swigCPtr, ctype, x, y, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawDotMap(int x, int y, Color color) {
    bridgePINVOKEProxy.Game_drawDotMap(swigCPtr, x, y, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawDotMouse(int x, int y, Color color) {
    bridgePINVOKEProxy.Game_drawDotMouse(swigCPtr, x, y, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawDotScreen(int x, int y, Color color) {
    bridgePINVOKEProxy.Game_drawDotScreen(swigCPtr, x, y, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawLine(int ctype, int x1, int y1, int x2, int y2, Color color) {
    bridgePINVOKEProxy.Game_drawLine(swigCPtr, ctype, x1, y1, x2, y2, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawLineMap(int x1, int y1, int x2, int y2, Color color) {
    bridgePINVOKEProxy.Game_drawLineMap(swigCPtr, x1, y1, x2, y2, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawLineMouse(int x1, int y1, int x2, int y2, Color color) {
    bridgePINVOKEProxy.Game_drawLineMouse(swigCPtr, x1, y1, x2, y2, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public virtual void drawLineScreen(int x1, int y1, int x2, int y2, Color color) {
    bridgePINVOKEProxy.Game_drawLineScreen(swigCPtr, x1, y1, x2, y2, Color.getCPtr(color));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

}

}
