/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public partial class PositionVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerable<Position>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PositionVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PositionVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PositionVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKEProxy.delete_PositionVector(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PositionVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (Position element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Position this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(Position[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(Position[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, Position[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<Position> System.Collections.Generic.IEnumerable<Position>.GetEnumerator() {
    return new PositionVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new PositionVectorEnumerator(this);
  }

  public PositionVectorEnumerator GetEnumerator() {
    return new PositionVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class PositionVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<Position>
#endif
  {
    private PositionVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public PositionVectorEnumerator(PositionVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Position Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (Position)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    bridgePINVOKEProxy.PositionVector_Clear(swigCPtr);
  }

  public void Add(Position x) {
    bridgePINVOKEProxy.PositionVector_Add(swigCPtr, Position.getCPtr(x));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = bridgePINVOKEProxy.PositionVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = bridgePINVOKEProxy.PositionVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    bridgePINVOKEProxy.PositionVector_reserve(swigCPtr, n);
  }

  public PositionVector() : this(bridgePINVOKEProxy.new_PositionVector__SWIG_0(), true) {
  }

  public PositionVector(PositionVector other) : this(bridgePINVOKEProxy.new_PositionVector__SWIG_1(PositionVector.getCPtr(other)), true) {
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public PositionVector(int capacity) : this(bridgePINVOKEProxy.new_PositionVector__SWIG_2(capacity), true) {
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  private Position getitemcopy(int index) {
    Position ret = new Position(bridgePINVOKEProxy.PositionVector_getitemcopy(swigCPtr, index), true);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  private Position getitem(int index) {
    Position ret = new Position(bridgePINVOKEProxy.PositionVector_getitem(swigCPtr, index), false);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Position val) {
    bridgePINVOKEProxy.PositionVector_setitem(swigCPtr, index, Position.getCPtr(val));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public void AddRange(PositionVector values) {
    bridgePINVOKEProxy.PositionVector_AddRange(swigCPtr, PositionVector.getCPtr(values));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public PositionVector GetRange(int index, int count) {
    IntPtr cPtr = bridgePINVOKEProxy.PositionVector_GetRange(swigCPtr, index, count);
    PositionVector ret = (cPtr == IntPtr.Zero) ? null : new PositionVector(cPtr, true);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Position x) {
    bridgePINVOKEProxy.PositionVector_Insert(swigCPtr, index, Position.getCPtr(x));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, PositionVector values) {
    bridgePINVOKEProxy.PositionVector_InsertRange(swigCPtr, index, PositionVector.getCPtr(values));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    bridgePINVOKEProxy.PositionVector_RemoveAt(swigCPtr, index);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    bridgePINVOKEProxy.PositionVector_RemoveRange(swigCPtr, index, count);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public static PositionVector Repeat(Position value, int count) {
    IntPtr cPtr = bridgePINVOKEProxy.PositionVector_Repeat(Position.getCPtr(value), count);
    PositionVector ret = (cPtr == IntPtr.Zero) ? null : new PositionVector(cPtr, true);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    bridgePINVOKEProxy.PositionVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    bridgePINVOKEProxy.PositionVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, PositionVector values) {
    bridgePINVOKEProxy.PositionVector_SetRange(swigCPtr, index, PositionVector.getCPtr(values));
    if (bridgePINVOKEProxy.SWIGPendingException.Pending) throw bridgePINVOKEProxy.SWIGPendingException.Retrieve();
  }

}

}
