/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace BWAPI {

using System;
using System.Runtime.InteropServices;

public class BaseLocationSpacelessSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BaseLocationSpacelessSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(BaseLocationSpacelessSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~BaseLocationSpacelessSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_BaseLocationSpacelessSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public BaseLocationSpacelessSet(SWIGTYPE_p_std__setT_BWTA__BaseLocation_p_t original) : this(bridgePINVOKE.new_BaseLocationSpacelessSet(SWIGTYPE_p_std__setT_BWTA__BaseLocation_p_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.BaseLocationSpacelessSet_size(swigCPtr);
    return ret;
  }

  public bool contains(BaseLocation item) {
    bool ret = bridgePINVOKE.BaseLocationSpacelessSet_contains(swigCPtr, BaseLocation.getCPtr(item));
    return ret;
  }

  public bool add(BaseLocation item) {
    bool ret = bridgePINVOKE.BaseLocationSpacelessSet_add(swigCPtr, BaseLocation.getCPtr(item));
    return ret;
  }

  public void clear() {
    bridgePINVOKE.BaseLocationSpacelessSet_clear(swigCPtr);
  }

  public bool remove(BaseLocation item) {
    bool ret = bridgePINVOKE.BaseLocationSpacelessSet_remove(swigCPtr, BaseLocation.getCPtr(item));
    return ret;
  }

}

}
