/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class Force : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Force(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Force obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Force() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_Force(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual string getName() {
    string ret = bridgePINVOKE.Force_getName(swigCPtr);
    return ret;
  }

  public virtual SWIGTYPE_p_std__setT_BWAPI__Player_p_t getPlayers() {
    SWIGTYPE_p_std__setT_BWAPI__Player_p_t ret = new SWIGTYPE_p_std__setT_BWAPI__Player_p_t(bridgePINVOKE.Force_getPlayers(swigCPtr), true);
    return ret;
  }

}
