/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PlayerType : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PlayerType(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PlayerType obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PlayerType() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_PlayerType(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public PlayerType() : this(bridgePINVOKE.new_PlayerType__SWIG_0(), true) {
  }

  public PlayerType(int id) : this(bridgePINVOKE.new_PlayerType__SWIG_1(id), true) {
  }

  public PlayerType(PlayerType other) : this(bridgePINVOKE.new_PlayerType__SWIG_2(PlayerType.getCPtr(other)), true) {
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
  }

  public PlayerType opAssign(PlayerType other) {
    PlayerType ret = new PlayerType(bridgePINVOKE.PlayerType_opAssign(swigCPtr, PlayerType.getCPtr(other)), false);
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opEquals(PlayerType other) {
    bool ret = bridgePINVOKE.PlayerType_opEquals(swigCPtr, PlayerType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opNotEquals(PlayerType other) {
    bool ret = bridgePINVOKE.PlayerType_opNotEquals(swigCPtr, PlayerType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool opLessThan(PlayerType other) {
    bool ret = bridgePINVOKE.PlayerType_opLessThan(swigCPtr, PlayerType.getCPtr(other));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getID() {
    int ret = bridgePINVOKE.PlayerType_getID(swigCPtr);
    return ret;
  }

  public string getName() {
    string ret = bridgePINVOKE.PlayerType_getName(swigCPtr);
    return ret;
  }

}
