/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class RaceSet : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RaceSet(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(RaceSet obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~RaceSet() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bridgePINVOKE.delete_RaceSet(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public RaceSet(SWIGTYPE_p_std__setT_BWAPI__Race_t original) : this(bridgePINVOKE.new_RaceSet(SWIGTYPE_p_std__setT_BWAPI__Race_t.getCPtr(original)), true) {
  }

  public int size() {
    int ret = bridgePINVOKE.RaceSet_size(swigCPtr);
    return ret;
  }

  public bool contains(Race item) {
    bool ret = bridgePINVOKE.RaceSet_contains(swigCPtr, Race.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool add(Race item) {
    bool ret = bridgePINVOKE.RaceSet_add(swigCPtr, Race.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void clear() {
    bridgePINVOKE.RaceSet_clear(swigCPtr);
  }

  public bool remove(Race item) {
    bool ret = bridgePINVOKE.RaceSet_remove(swigCPtr, Race.getCPtr(item));
    if (bridgePINVOKE.SWIGPendingException.Pending) throw bridgePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
